Занятие 1: Основы JavaScript.
js-tasks-ru/jsbasic-20210621_gregory9 pull request #2
Opened 2021-06-28 17:02 UTC by gmakeev

Занятие 1: Основы JavaScript.
Задачи выполнены.

2021-06-28 17:03 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-06-28 19:07 UTC, SinimaWath requested changes

2021-06-28 19:07 UTC, SinimaWath commented on 1-module/1-task/index.js
> +  return resultF;
Давай немного избавимся от вложенности:
```
if () {
 ...
 return ...;
}

for () {
...
}
```

https://refactoring.guru/ru/replace-nested-conditional-with-guard-clauses

2021-06-28 19:07 UTC, SinimaWath commented on 1-module/2-task/index.js
> +  }
Давай попробуем в одну строчку ;) `return ....`

2021-06-28 19:07 UTC, SinimaWath commented on 1-module/3-task/index.js
> +  }
- нет необходимости в else
- можно не создавать временную переменную newStr

2021-06-28 19:07 UTC, SinimaWath commented on 1-module/4-task/index.js
> +      let resultCheck = null;
кажется не нужная переменная

2021-06-28 19:07 UTC, SinimaWath commented on 1-module/5-task/index.js
> +  }
можно без else;
```
if () {
  return;
}

return;
```

2021-06-29 06:41 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-06-29 20:50 UTC, SinimaWath requested changes

2021-06-29 20:50 UTC, SinimaWath commented on 1-module/2-task/index.js
> +  return (name == null || name.length < 4 || name.includes(' ')) ? false : true
Результат операции: `(name == null || name.length < 4 || name.includes(' '))`, уже возвращает true/false, так что нет необходимости в тернарном операторе: ?

2021-06-29 20:50 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  }
Результат операции `lowerStr.includes('1xbet') || lowerStr.includes('xxx')`, уже и есть boolean. Так что можно сразу вернуть в `return lowerStr.includes('1xbet') || lowerStr.includes('xxx')`

2021-06-29 20:50 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  let lowerStr = str.toLowerCase();
Все таки это const

2021-06-30 11:32 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-07-01 11:45 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2021-07-01 11:53 UTC, gmakeev commented
Lesson 2. Objects. Tasks were done.

2021-07-01 11:54 UTC, gmakeev commented
Lesson 2. Objects. Tasks 1,2,3 were done.

2021-07-01 11:54 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @SinimaWath

2021-07-01 15:29 UTC, SinimaWath requested changes
давай уберем из всех задач, код для тестирования, в котором ты вызыаешь функцию сам.

для тестирования используй npm test

2021-07-01 15:29 UTC, SinimaWath commented on 2-module/1-task/index.js
> +    }
Не понимаю, зачем тут тебе второй вложенный цикл. `for (let salary in salaries) ` и `for (let key in salaries)`, одинаковые циклы.

Давай оставим только один

2021-07-01 15:29 UTC, SinimaWath commented on 2-module/1-task/index.js
> +    }
Также  `&& isNaN(salaries[key]) !== true && isFinite(salaries[key]) == true`, можно сократить до `&& isNaN(salaries[key]) && isFinite(salaries[key])`

2021-07-02 06:56 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2021-07-02 14:02 UTC, SinimaWath approved these changes

2021-07-02 14:03 UTC, merged